import type { Platform } from '../../../types'
import { BaseSocialConnector } from '../BaseSocialConnector'
import type { CredentialProvider, SocialPostRequest, SocialPostResult } from '../types'
import { SocialError } from '../types'

/**
 * Bluesky connector — publishes posts via the AT Protocol lexicon.
 *
 * API reference: https://docs.bsky.app/docs/api/app-bsky-feed-create-post
 *
 * AT Protocol OAuth specifics:
 *   - Access tokens are DPoP-bound (RFC 9449). Every API call needs both an
 *     `Authorization: DPoP <token>` header AND a fresh `DPoP: <proof>` header.
 *   - The DPoP proof is generated by {@link BlueskyDPoPCredentials}, which
 *     keeps the ES256 private key server-side.
 *   - The posting endpoint is the user's PDS (Personal Data Server), which
 *     varies per account and is stored alongside the access token.
 *
 * Character limit: 300 graphemes (Bluesky counts by Unicode grapheme clusters,
 * not UTF-16 code units). This connector approximates grapheme count using the
 * `Intl.Segmenter` API when available, falling back to code-point count.
 */

export const BLUESKY_CHAR_LIMIT = 300

/** Bluesky scopes requested during the OAuth flow. */
export const BLUESKY_SCOPE = 'atproto transition:generic'

/**
 * Extended credential interface for Bluesky's DPoP-bound tokens.
 *
 * Callers (the server publish route) must supply an implementation that
 * provides both the access token AND can generate fresh DPoP proofs using
 * the stored ES256 private key.
 */
export interface BlueskyCredentials extends CredentialProvider {
  /**
   * Create a DPoP proof JWT for the given HTTP method and URL.
   *
   * @param method      Uppercase HTTP method (e.g. "POST").
   * @param url         Absolute request URL (scheme + authority + path, no query/fragment).
   * @param accessToken The current access token — its SHA-256 hash is included as `ath`.
   * @param nonce       Optional nonce from a previous `DPoP-Nonce` response header.
   */
  createDPoPProof(method: string, url: string, accessToken: string, nonce?: string): string
}

export function isBlueskyCredentials(creds: CredentialProvider): creds is BlueskyCredentials {
  return typeof (creds as BlueskyCredentials).createDPoPProof === 'function'
}

/**
 * Count Bluesky graphemes.
 *
 * Bluesky enforces a 300-grapheme limit using the Unicode grapheme cluster
 * algorithm. We use `Intl.Segmenter` (available in Node 18+ and modern
 * browsers) when available, and fall back to `[...text].length` (code-point
 * count, which is close but may differ on complex emoji sequences).
 */
export function countGraphemes(text: string): number {
  if (typeof Intl !== 'undefined' && 'Segmenter' in Intl) {
    const segmenter = new (Intl as typeof Intl & { Segmenter: new (locale?: string, opts?: { granularity?: string }) => { segment: (s: string) => Iterable<unknown> } }).Segmenter(undefined, { granularity: 'grapheme' })
    return [...segmenter.segment(text)].length
  }
  // Fallback: count Unicode code points (Array spread splits on surrogate pairs)
  return [...text].length
}

export class BlueskyConnector extends BaseSocialConnector {
  readonly platform: Platform = 'bluesky'
  readonly charLimit = BLUESKY_CHAR_LIMIT

  override countCharacters(text: string): number {
    return countGraphemes(text)
  }

  /**
   * Publish a post to Bluesky via the AT Protocol.
   *
   * `request.bluesky` must be populated with the user's DID and PDS URL.
   * `credentials` must implement {@link BlueskyCredentials} (provides DPoP proofs).
   *
   * @throws {SocialError} on API errors or if Bluesky-specific fields are missing.
   */
  async post(request: SocialPostRequest, credentials: CredentialProvider): Promise<SocialPostResult> {
    if (!isBlueskyCredentials(credentials)) {
      throw new SocialError(
        'BlueskyConnector requires BlueskyCredentials with createDPoPProof() support',
        { platform: 'bluesky', retryable: false },
      )
    }

    const { did, pdsUrl } = request.bluesky ?? {}
    if (!did || !pdsUrl) {
      throw new SocialError(
        'Bluesky posts require request.bluesky.did and request.bluesky.pdsUrl',
        { platform: 'bluesky', retryable: false },
      )
    }

    // Enforce the grapheme-based character limit before sending.
    const { content, hashtags } = this.enforceLimit(request.content, request.hashtags ?? [])
    const text = this.buildCombinedText(content, hashtags)

    const url = `${pdsUrl}/xrpc/com.atproto.repo.createRecord`
    const accessToken = await credentials.getAccessToken()

    const record: Record<string, unknown> = {
      $type: 'app.bsky.feed.post',
      text,
      createdAt: new Date().toISOString(),
      langs: ['en'],
    }

    const body = {
      repo: did,
      collection: 'app.bsky.feed.post',
      record,
    }

    // Attempt the request, handling DPoP nonce challenges with one retry.
    const makeRequest = async (nonce?: string): Promise<Response> => {
      const dpopProof = credentials.createDPoPProof('POST', url, accessToken, nonce)
      return this.safeFetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `DPoP ${accessToken}`,
          DPoP: dpopProof,
          'User-Agent': 'AutoMarketer/1.0',
        },
        body: JSON.stringify(body),
      })
    }

    let response: Response
    try {
      response = await makeRequest()

      // Handle DPoP nonce challenge — the PDS returns 401 with
      // error=use_dpop_nonce and a DPoP-Nonce header. Retry once.
      if (response.status === 401) {
        const nonce = response.headers.get('DPoP-Nonce')
        if (nonce) {
          const errBody = await response.json().catch(() => ({})) as { error?: string }
          if (errBody.error === 'use_dpop_nonce') {
            response = await makeRequest(nonce)
          }
        }
      }
    } catch (err) {
      throw new SocialError(
        `Network error contacting Bluesky PDS: ${err instanceof Error ? err.message : String(err)}`,
        { platform: 'bluesky', retryable: false },
      )
    }

    if (!response.ok) {
      let rawResponse = ''
      try {
        rawResponse = await response.text()
      } catch {
        // ignore read errors
      }
      throw new SocialError(`Bluesky API error ${response.status}: ${rawResponse}`, {
        httpStatus: response.status,
        platform: 'bluesky',
        rawResponse,
        retryable: response.status === 429 || response.status >= 500,
      })
    }

    const data = (await response.json().catch(() => ({}))) as {
      uri?: string
      cid?: string
    }

    // The URI is in the format "at://did:plc:.../app.bsky.feed.post/..."
    // Convert to a web URL: https://bsky.app/profile/{did}/post/{rkey}
    const postUri = data.uri ?? ''
    const rkey = postUri.split('/').pop()
    const webUrl = rkey ? `https://bsky.app/profile/${encodeURIComponent(did)}/post/${rkey}` : undefined

    return {
      success: true,
      platform: 'bluesky',
      postId: data.cid ?? rkey,
      url: webUrl,
    }
  }
}
